# Generated by Django 4.1 on 2022-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=170, unique=True)),
                ('check_flag', models.TextField(max_length=170)),
                ('check_flag2', models.TextField(max_length=170)),
                ('check_flag3', models.TextField(max_length=170)),
                ('finish', models.TextField(max_length=400)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('youtube_video', models.CharField(max_length=1000)),
            ],
        ),
    ]
