# Generated by Django 4.1 on 2022-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='count',
            field=models.IntegerField(),
        ),
    ]
