# Generated by Django 4.1 on 2022-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_stats_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(max_length=300)),
                ('my_url', models.URLField()),
                ('header1', models.CharField(max_length=40)),
                ('text1', models.TextField(max_length=200)),
                ('header2', models.CharField(max_length=40)),
                ('text2', models.TextField(max_length=200)),
                ('header3', models.CharField(max_length=40)),
                ('text3', models.TextField(max_length=200)),
            ],
        ),
    ]
