# Generated by Django 4.1 on 2022-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_why_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('discription', models.TextField(blank=True, max_length=70)),
                ('watch_video', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
