# Generated by Django 4.1 on 2022-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_home_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='discription',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='home',
            name='header',
            field=models.CharField(max_length=70),
        ),
    ]
