# Generated by Django 4.1 on 2022-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_home_discription_alter_home_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='dishes',
            index_together={('id', 'slug')},
        ),
    ]
