# Generated by Django 4.1 on 2022-08-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_dishes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='categories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.categories'),
            preserve_default=False,
        ),
    ]
