# Generated by Django 4.1 on 2022-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_dishes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('comment', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
