# Generated by Django 4.1 on 2022-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
