# Generated by Django 4.1 on 2022-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_address', models.CharField(max_length=200)),
                ('call_us', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('opening', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.TextField(max_length=600)),
                ('admin_date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-admin_date', '-is_processed'),
            },
        ),
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('persons', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=500)),
                ('admin_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.CharField(max_length=70)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-admin_date', '-is_processed'),
            },
        ),
    ]
