# Generated by Django 4.1 on 2022-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_userreservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='stars',
            field=models.SmallIntegerField(default=5),
        ),
    ]
